### ISSUE TITLE
Installing development dependancies results in 'FileNotFound' error

### ISSUE THREAD

**Issue by nicolaiskye** [pybitcash/bitcash#93]
# Description
When attempting to build and test the Bitcash library in an isolated environment, installing the development dependancies (needed for running tests) results in an error. Despite this error occurring, running `python3 run_tests.py` afterward still does appear to work. I'm able to run all tests successfully.

# Steps to Reproduce
1. Clone Bitcash repo
1.5. (Optional. Setup virtual environment folder) `virtualenv ./venv`
2. `python3 setup.py build`
3. `python3 setup.py install`
4. `pip3 install -r requirements-dev.txt`

# Error Message
```
Traceback (most recent call last):
  File "/Users/nick/dev/bfp/bitcash/venv/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 226, in _main
    self.handle_pip_version_check(options)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 145, in handle_pip_version_check
    session = self._build_session(
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 86, in _build_session
    session = PipSession(
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 245, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 159, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 644, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nick/dev/bfp/bitcash/venv/lib/python3.9/site-packages/bitcash-0.6.1-py3.9.egg'
```

**Comment by teran-mckinney** [comment]
Interesting. I'll have to try reproducing this sometime. I haven't used Python 3.9 yet. Might be part of it.

**Comment by merc1er** [comment]
Are you still having this issue @nicolaiskye ?
